# Generated by Django 3.2 on 2022-06-04 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_votante', '0002_registrovotantemodel_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrovotantemodel',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
