# Generated by Django 3.2 on 2022-06-03 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampanaModel',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='nombre', max_length=255, null=True)),
                ('eslogan', models.CharField(blank=True, db_column='eslogan', max_length=255, null=True)),
                ('logo', models.FileField(blank=True, db_column='logo', null=True, upload_to='soporte/')),
                ('partido', models.CharField(blank=True, db_column='partido', max_length=255, null=True)),
                ('candidato', models.CharField(blank=True, db_column='candidato', max_length=255, null=True)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True, db_column='fecha_ingreso', null=True)),
            ],
            options={
                'verbose_name': 'Campaña',
                'verbose_name_plural': 'Campaña',
                'db_table': 'campana',
                'managed': True,
            },
        ),
    ]
