# Generated by Django 3.2 on 2022-06-03 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DivipolModel',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('referencia', models.CharField(blank=True, max_length=60, null=True, unique=True)),
                ('comentario', models.CharField(blank=True, max_length=60, null=True)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True, db_column='fecha_ingreso', null=True)),
                ('ciudad', models.ForeignKey(db_column='ciudad', on_delete=django.db.models.deletion.DO_NOTHING, to='config.ciudadmodel')),
                ('departamento', models.ForeignKey(db_column='departamento', on_delete=django.db.models.deletion.DO_NOTHING, to='config.departamentomodel')),
            ],
            options={
                'verbose_name': 'Divipol',
                'verbose_name_plural': 'Divipol',
                'db_table': 'divipol',
                'managed': True,
            },
        ),
    ]
