# Generated by Django 3.2 on 2022-06-03 06:14

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('campana', '0001_initial'),
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nodocumento', models.BigIntegerField(blank=True, null=True)),
                ('nombre', models.CharField(db_column='nombre', max_length=45)),
                ('apellido', models.CharField(db_column='apellido', max_length=45)),
                ('movil', models.IntegerField(blank=True, db_column='movil', null=True)),
                ('fijo', models.IntegerField(blank=True, db_column='fijo', null=True)),
                ('direccion', models.CharField(db_column='direccion', max_length=70)),
                ('firma', models.FileField(blank=True, null=True, upload_to='soporte/')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_manager', models.BooleanField(default=False)),
                ('is_lider', models.BooleanField(default=False)),
                ('campana', models.ForeignKey(blank=True, db_column='campana', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='campana.campanamodel')),
                ('ciudad', models.ForeignKey(blank=True, db_column='ciudad', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='config.ciudadmodel')),
                ('departamento', models.ForeignKey(blank=True, db_column='departamento', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='config.departamentomodel')),
                ('genero', models.ForeignKey(blank=True, db_column='genero', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='config.generomodel')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('tipo_documento', models.ForeignKey(blank=True, db_column='tipo_documento', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='config.tipodocumentomodel')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'auth_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='VotanteModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nodocumento', models.BigIntegerField(blank=True, null=True)),
                ('nombre', models.CharField(db_column='nombre', max_length=45)),
                ('apellido', models.CharField(db_column='apellido', max_length=45)),
                ('movil', models.IntegerField(blank=True, db_column='movil', null=True)),
                ('direccion', models.CharField(db_column='direccion', max_length=70)),
                ('firma', models.FileField(blank=True, null=True, upload_to='soporte/')),
                ('ciudad', models.ForeignKey(blank=True, db_column='ciudad', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='config.ciudadmodel')),
                ('departamento', models.ForeignKey(blank=True, db_column='departamento', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='config.departamentomodel')),
                ('genero', models.ForeignKey(blank=True, db_column='genero', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='config.generomodel')),
                ('tipo_documento', models.ForeignKey(blank=True, db_column='tipo_documento', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='config.tipodocumentomodel')),
                ('user', models.ForeignKey(blank=True, db_column='usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'votante',
                'verbose_name_plural': 'votante',
                'db_table': 'votante',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ManagerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=64)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LiderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=64)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=64)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
