# Generated by Django 3.2 on 2022-06-03 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zona_votacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuestoVotacionModel',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=150, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=60)),
                ('mesa', models.IntegerField()),
                ('potencial', models.IntegerField()),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True, db_column='fecha_ingreso', null=True)),
                ('zona', models.ForeignKey(db_column='zona', on_delete=django.db.models.deletion.CASCADE, to='zona_votacion.zonavotacionmodel')),
            ],
            options={
                'verbose_name': 'puesto votacion',
                'verbose_name_plural': 'puesto de votaciones',
                'db_table': 'puesto_votacion',
                'managed': True,
            },
        ),
    ]
